server:
  ssl:
    # 证书路径
    key-store: classpath:server.keystore
    key-alias: server
    enabled: true
    key-store-type: JKS
    #与申请时输入一致
    key-store-password: 123456
  # 浏览器默认端口 和 80 类似，https默认的端口号为443
  port: 443
