server:
  # 端口号
  port: 8888
  servlet:
    # 项目前缀
    context-path: /swagger
spring:
  swagger:
    enabled: true
    # 项目标题
    title: spring-boot-swagger
    # 项目说明
    description: 这是一个简单的 Swagger API 演示
    # 版本号，自己定义
    version: 1.0.0
    contact:
      # 自己的信息
      name: zhouzhaodong
      email: xiuaiba@163.com
      url: http://www.zhouzhaodong.xyz
    # swagger扫描的基础包，默认：全扫描
    # base-package:
    # 需要处理的基础URL规则，默认：/**
    # base-path:
    # 需要排除的URL规则，默认：空
    # exclude-path:
    security:
      # 是否启用 swagger 登录验证
      filter-plugin: true
      # 账号
      username: zhouzhaodong
      # 密码
      password: 123456
    # 相关错误说明
    global-response-messages:
      GET[0]:
        code: 400
        message: Bad Request，这个错误一般情况下为请求参数不对
      GET[1]:
        code: 404
        message: NOT FOUND，这个错误一般情况下为请求路径不对
      GET[2]:
        code: 500
        message: ERROR，这个错误一般情况下为程序内部错误
      POST[0]:
        code: 400
        message: Bad Request，这个错误一般情况下为请求参数不对
      POST[1]:
        code: 404
        message: NOT FOUND，这个错误一般情况下为请求路径不对
      POST[2]:
        code: 500
        message: ERROR，这个错误一般情况下为程序内部错误