server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://IP地址:3306/querydsl?characterEncoding=UTF-8
    username: 用户名
    password: 密码
  jpa:
    show-sql: true # 控制台打印SQL
    hibernate:
      ddl-auto: update